spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSql
    username: test
    password: test
    driver-class-name: org.h2.Driver
  mvc:
    pathmatch:
      #a workaround for springfox which doesn't support spring boot 2.6.x
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
reminders:
  executors:
    on-startup:
      mode:
        parallel
    scheduled:
      mode:
        parallel
  actions:
    smtp:
      sender-address: noreply-reminder@asdad.com
  execution:
    parallelism: 5
logging:
  level:
    root: info