spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSql
    username: test
    password: test
    driver-class-name: org.h2.Driver
  #a workaround for springfox which doesn't support spring boot 2.6.x
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher